# 如果 application.properties 和 application.yml 中有相同的配置，以 application.properties 的为准
# 官方文档，讲解了所有配置属性
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/


spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/fengshiqing?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: fengshiqing
    password: fengshiqing

  data:
    redis:
      host: 192.168.0.100
      port: 6379 # Redis服务器连接密码（默认为空）
      password:  # Redis服务器连接密码（默认为空）
      database: 0 # Redis数据库索引（默认为0）
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数（使用负值表示没有限制），默认 8
          max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制），默认 -1
          max-idle: 8  # 连接池中的最大空闲连接，默认 8
          min-idle: 1  # 连接池中的最小空闲连接，默认 0
      timeout: 3000  # 连接超时时间（毫秒）

  config:
    import:
      - optional:nacos:${spring.application.name}.properties?namespace=dev&group=DEFAULT_GROUP
  nacos:
    config:
      server-addr: 192.168.0.100:8848
      username: nacos
      password: nacos
      file-extension: properties


aa: 本地环境
user:
  id: 1
  age: 18
  sex: 1
  name: fengshiqing